// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./components/Footer.vue')['default']
    NavigationBar: typeof import('./components/NavigationBar.vue')['default']
    PostList: typeof import('./components/PostList.vue')['default']
    README: typeof import('./components/README.md')['default']
  }
}

export { }
